import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="fixed flex inset-0 bg-white dark:bg-black sm:px-8">
					<div className="w-full max-w-7xl lg:px-8 bg-amber-50"></div>
				</div>
				<div className="relative main w-full h-full sm:px-8">
					<div className="w-full max-w-7xl lg:px-8">
						<div className="text-3xl">header</div>
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
