name: GitHub Discussions Notifier

on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]

jobs:
  notify-github-discussions:
    # runs-on: ubuntu-latest
    with:
      status: custom
      custom_payload: |
        {
          "text": "New Discussion Alert!",
        }
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
    # steps:
    #   - uses: 8398a7/action-slack@v3
    #     with:
    #       status: ${{ job.status }}
    #       fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
    #     env:
    #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
    #     if: always() # Pick up events even if the job fails or is canceled.
